nodeLinker: pnp
# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs

# This section is for dependencies that ar used by other dependencies and are not placed
# somewhere in our dependencies. For example, here chalk is used by lfd-utils which is a direct
# dependency used by tests/backend/commonjs. To solve problem caused by this we can add 
# #ansi-styles and #supports-color to the dependencies of tests/backend/commonjs... or do this
packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2